### ISSUE TITLE
Concern regarding safety

### ISSUE THREAD

**Issue by StoneCypher** [WebKit/explainers#29] opened 2020-02-03 16:33 UTC
SMS is well known to be deeply insecure, and highly inappropriate for transferring temporary credentials.  This has been one of the most frequent vectors of high touch real world attacks, including against Apple

The sophistication of actors, users, and even carriers will not help.  By example, the OTA provisioning mis-feature in Android, that allows a phone carrier to silently remotely install software on my phone without my consent, was [repeatedly abused by attackers in the real world](https://thenextweb.com/security/2019/09/04/hackers-are-now-attacking-android-users-with-advanced-sms-phishing-techniques/) to compromise hundreds of thousands of devices

Is it appropriate at this point to move forward with SMS as a network layer?

**Comment by hober** [comment] 2020-02-03 22:13
Duplicate of #10.

**Closed by hober** 2020-02-03 22:13 UTC
Labels: one time codes

**Comment by StoneCypher** [comment] 2020-02-03 23:00
This issue offers significant extra context and evidence of well known real world abuse at large scale

That evidence was lost in this transaction, because this issue was linked to a different closed issue.  I've gone to the actual active issue about this, and re-raised the evidence that ***this design strategy is frequently abused in the real world with total device takeover as the consequence***.

**Comment by StoneCypher** [comment] 2020-02-03 23:01
i've done my best ☹️
